### ISSUE TITLE
Aria Digital Twin Download Links JSON file doesn't work with aria_dataset_downloader

### ISSUE THREAD

**Issue by relh** [facebookresearch/projectaria_tools#112]
Hi everyone!

I am trying to download the Aria digital twin dataset but I've run into this error. To me it looks like the json file I got from the Aria Digital Twin Download link is missing a key needed for the dataset downloader. Presumably I can download each link on its own but I'm assuming that this is supposed to work out of the box (given its in the instructions on `https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset/dataset_download`. Does anyone know how to fix this? 

```
aria_dataset_downloader -c /mnt/sda/aria_digital_twin_dataset_download_urls.json \
-o /mnt/sda/projectaria_tools_adt_data/ \
-l Apartment_release_golden_skeleton_seq100_10s_sample_M1292 \
-d 0 1 2 3 4 5 6 7 8 9

Traceback (most recent call last):
  File "/home/relh/miniforge3/bin/aria_dataset_downloader", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/relh/miniforge3/lib/python3.11/site-packages/projectaria_tools/utils/datasets/dataset_downloader_main.py", line 86, in main
    all_data_groups = load_data_groups_from_cdn(args.cdn_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/relh/miniforge3/lib/python3.11/site-packages/projectaria_tools/utils/datasets/dataset_downloader_utils.py", line 101, in load_data_groups_from_cdn
    raise Exception("invalid cdn_file, missing key: sequence_config")
Exception: invalid cdn_file, missing key: sequence_config
```

**Comment by relh** [comment]
The deprecated downloader also doesn't work (as its deprecated I presume):

```
adt_benchmark_dataset_downloader -c /mnt/sda/aria_digital_twin_dataset_download_urls.json \
-o /mnt/sda/projectaria_tools_adt_data/ \
-l Apartment_release_golden_skeleton_seq100_10s_sample_M1292 \
-d 0 1 2 3 4 5 6 7 8 9
Traceback (most recent call last):
  File "/home/relh/miniforge3/bin/adt_benchmark_dataset_downloader", line 5, in <module>
    from projectaria_tools.projects.adt.adt_benchmark_dataset_downloader import main
ImportError: cannot import name 'main' from 'projectaria_tools.projects.adt.adt_benchmark_dataset_downloader' (/home/relh/miniforge3/lib/python3.11/site-packages/projectaria_tools/projects/adt/adt_benchmark_dataset_downloader.py)
```

**Comment by relh** [comment]
And this alternate command also gives the same error as initially:

```
aria_dataset_downloader --cdn_file /mnt/sda/aria_digital_twin_dataset_download_urls.json --output_folder /mnt/sda/projectaria_tools_adt_data --data_types 0 6 
Traceback (most recent call last):
  File "/home/relh/miniforge3/bin/aria_dataset_downloader", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/relh/miniforge3/lib/python3.11/site-packages/projectaria_tools/utils/datasets/dataset_downloader_main.py", line 86, in main
    all_data_groups = load_data_groups_from_cdn(args.cdn_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/relh/miniforge3/lib/python3.11/site-packages/projectaria_tools/utils/datasets/dataset_downloader_utils.py", line 101, in load_data_groups_from_cdn
    raise Exception("invalid cdn_file, missing key: sequence_config")
Exception: invalid cdn_file, missing key: sequence_config
```

**Comment by nickcharron** [comment]
Hi @relh, thanks for posting! I assume you got the downloads links file from projectaria.com/datasets/adt ?

Can you try downloading it from: https://explorer.projectaria.com/

It looks like the website hasn't been updated yet to point to the correct file. I will get this changes asap.

**Comment by relh** [comment]
Hi @nickcharron, this link worked. I was able to click the button "download found sequences" in the top right and use the json it gave me with the `aria_dataset_downloader` command like this:

`aria_dataset_downloader --cdn_file /mnt/sda/Aria_Digital_Twin_1720714131.json --output_folder /mnt/sda/projectaria_tools_adt_data --data_types 0 6`

Thanks for your quick response and help!

**Comment by nickcharron** [comment]
great, happy to hear! Closing this issue
