### ISSUE TITLE
Error for Digital Twin Catalogue Downloader

### ISSUE THREAD

**Issue by johannes-weidenfeller** [facebookresearch/projectaria_tools#141]
When using the aria_dataset_downloader (installed via pip) with the provided CDN file for the objects of the Digital Twin Catalogue, I get the following error:

```
aria_dataset_downloader --cdn_file aria/DTC_objects_download_urls.json --output_folder aria
Traceback (most recent call last):
  File "/home/weidenfj/miniconda3/envs/projectaria/bin/aria_dataset_downloader", line 8, in <module>
    sys.exit(main())
  File "/home/weidenfj/miniconda3/envs/projectaria/lib/python3.9/site-packages/projectaria_tools/utils/datasets/dataset_downloader_main.py", line 86, in main
    all_data_groups = load_data_groups_from_cdn(args.cdn_file)
  File "/home/weidenfj/miniconda3/envs/projectaria/lib/python3.9/site-packages/projectaria_tools/utils/datasets/dataset_downloader_utils.py", line 101, in load_data_groups_from_cdn
    raise Exception("invalid cdn_file, missing key: sequence_config")
Exception: invalid cdn_file, missing key: sequence_config
```

Downloading the VRS sequences works without problems. There seems to be a misconfiguration of the JSON file containing the object download URLs?

**Comment by johannes-weidenfeller** [comment]
I now realized I was supposed to use the dtc_object_downloader instead.
