### ISSUE TITLE
ASE Dataset downloading problem

### ISSUE THREAD

**Issue by thucz** [facebookresearch/projectaria_tools#96]
when I tried to download Scene 0-10000 of ASE, the downloading script failed at Scene 4700:
```
Traceback (most recent call last):                                                                                                                                                   
  File "/group/40033/public_datasets/3d_datasets/aria/projectaria_tools/projects/AriaSyntheticEnvironment/aria_synthetic_environments_downloader.py", line 149, in <module>          
    main(                                                                                                                                                                            
  File "/group/40033/public_datasets/3d_datasets/aria/projectaria_tools/projects/AriaSyntheticEnvironment/aria_synthetic_environments_downloader.py", line 128, in main              
    urllib.request.urlretrieve(                                                                                                                                                      
  File "/data/home/ozhengchen/anaconda3/lib/python3.9/urllib/request.py", line 278, in urlretrieve                                                                                   
    raise ContentTooShortError(                                                                                                                                                      
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 1257594816 out of 2878298873 bytes>
```

I rerun the download script, and it failed again. 

I also tried to skip Scene  4700. The code was stuck at the first chunk of the downloading process.
<img width="1280" alt="image" src="https://github.com/facebookresearch/projectaria_tools/assets/135981918/0d66c5c1-9a4d-4d84-b003-24192d6299ed">

It seems like downloading too many files made my IP blocked by your website.

I wonder how to avoid this problem.

**Comment by suvampatra** [comment]
Sorry for this, We tried downloading the same sequences and especially the ones pointed out above in the screenshot. We didn't face any issue downloading them. 

Its probably a network issue. Suggest trying downloading the missing sequences a different machine.

**Comment by thucz** [comment]
Thanks! Yes, I figured out that the network on my machine is not stable enough. I will try downloading that dataset on another machine
